spring.application.name=api-gateway
server.port=8080


# ========== EUREKA ==========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ========== GATEWAY ROUTING ==========
spring.cloud.gateway.discovery.locator.enabled=false

# optional log
logging.level.org.springframework.cloud.gateway=DEBUG

jwt.access.secret=yY7lhiu9nj+UZcbHVQ/pU+pvNswSFde0C3O8CXF2Oq8=

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=restaurant-service
spring.cloud.gateway.routes[1].uri=lb://restaurant-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/restaurants/**

spring.cloud.gateway.routes[2].id=restaurant-service
spring.cloud.gateway.routes[2].uri=lb://restaurant-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/menu-items/**

spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/cart/**

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://order-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/orders/**


spring.cloud.gateway.routes[5].id=order-service
spring.cloud.gateway.routes[5].uri=lb://order-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/customer-orders/**

spring.cloud.gateway.routes[6].id=order-service
spring.cloud.gateway.routes[6].uri=lb://order-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/restaurant-orders/**

spring.cloud.gateway.routes[7].id=payment-service
spring.cloud.gateway.routes[7].uri=lb://payment-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.routes[8].id=notification-service
spring.cloud.gateway.routes[8].uri=lb://notification-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notifications/**