spring.application.name=payment-service
logging.level.com.myproject.payment_service.util.VNPayUtil=DEBUG
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

vnpay.tmn-code=EPCK8MJR
vnpay.hash-secret=9M2UY8TO2UIVYJHGNAETXZDDGHYOY8LV

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

vnpay.return-url=http://localhost:8084/api/payments/vnpay-return

vnpay.ipn-url=http://localhost:8084/api/payments/vnpay-ipn

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest